import { Component, Inject, OnInit } from '@angular/core';
import { MAT_DIALOG_DATA } from '@angular/material/dialog';
import { MarketDisplay } from '../markets/components/market-display/market-display.model';
import { MarketsService } from '../markets/services/markets.service';
import { FactType } from '../risks/models/fact-type.enum';
import { Risk } from '../risks/models/risk.model';
import { AutoGeneratedRiskService } from '../risks/services/auto-generated-risk.service';
import { riskService } from '../risks/services/subjective-data.service';
import { RiskCatalystDialogInput } from './risk-catalyst-dialog-input.model';

@Component({
  selector: 'app-risk-catalyst-dialog',
  templateUrl: './risk-catalyst-dialog.component.html',
  styleUrls: ['./risk-catalyst-dialog.component.scss'],
})
export class RiskCatalystDialogComponent implements OnInit {
  readonly factTypeEnum = FactType;
  readonly factType;
  markets?: MarketDisplay[];
  risks?: Risk[];

  constructor(
    @Inject(MAT_DIALOG_DATA)
    dialogData: RiskCatalystDialogInput,
    private riskService: riskService,
    private marketsService: MarketsService,
    private autoGeneratedRiskService: AutoGeneratedRiskService
  ) {
    this.factType = dialogData.factType;
    if (dialogData.factType === FactType.business) {
      this.markets = marketsService.getMarketsByTypes(
        dialogData?.stock?.business?.markets
      );

      for (let market of this.markets) {
        market.risks = riskService.getRisksByUuids(market.riskUuids);
      }
    } else if (dialogData.factType === FactType.profit) {
      this.risks = this.autoGeneratedRiskService.getProfitabilityRisks(
        dialogData.stock
      );
    } else if (dialogData.factType === FactType.growth) {
      this.risks = this.autoGeneratedRiskService.getGrowthRisks(
        dialogData.stock
      );
    }
  }

  ngOnInit(): void {}
}
