export enum Source {
  axios = 'Axios',
  bloomberg = 'Bloomberg',
  BLOOMBERG = 'Bloomberg',
  BOA_GLOBAL_RESEARCH = '美银证券',
  CAR_THINGS = '车东西',
  CHINA_DAILY = '人民日报',
  cnbc = 'CNBC',
  earningReport = 'Earnings Report',
  investopedia = 'investopedia.com',
  Link = 'Link',
  MAD_MONEY = 'mad money',
  marketWatch = 'Market Watch',
  me = 'me',
  MORGAN_STANLEY = 'Morgan Stanley',
  Morningbrew = 'morningbrew.com',
  OFFICIAL = 'Earnings Report',
  reuters = 'Reuters',
  YAHOO = '雅虎财经',
  ibd = "Investor's Business Daily",
  electrek = 'Electrek',
}
