import { Injectable } from '@angular/core';
import { StockData } from 'src/app/stock/services/stock-data.model';
import { FactType } from '../models/fact-type.enum';
import { RiskLevel } from '../models/risk-level.model';
import { Risk } from '../models/risk.model';

export class Tag {}

@Injectable({
  providedIn: 'root',
})
export class AutoGeneratedRiskService {
  constructor() {}

  getProfitabilityRisks(stock: StockData): Risk[] {
    const risks: Risk[] = [];
    if (stock.quarterGrossProfitGrowth < stock.quarterExpensesGrowth) {
      risks.push({
        type: FactType.profit,
        content: `${stock.shortName}'s operating margin is decreasing.`,
        level: RiskLevel.shortTerm,
      });
    }

    if (stock.quarterOperatingCostOverGrossProfit > 1) {
      risks.push({
        type: FactType.profit,
        content: `${stock.shortName} is not able to earn income.`,
        level: RiskLevel.shortTerm,
      });
    }

    return risks;
  }

  getGrowthRisks(stock: StockData): Risk[] {
    const risks: Risk[] = [];

    if (stock.quarterRevenueGrowth < 0.1) {
      risks.push({
        type: FactType.growth,
        content: `${stock.shortName}'s revenue growth is only single digit.`,
        level: RiskLevel.longTerm,
      });
    } else if (
      stock.quarterRevenueGrowth / stock.yearOverYearRevenueGrowth <
      0.5
    ) {
      risks.push({
        type: FactType.growth,
        content: `${stock.shortName}'s revenue growth slows down significantly`,
        level: RiskLevel.shortTerm,
      });
    }

    return risks;
  }
}
